---
become_override: false
ocp_username: admin
silent: false

# If your workload needs customization options provide variables to be used.
# Variable names must be prefixed by the role name "<role name>_<variable>".
# So because this example workload is called "ocp4_workload_example" the variables
# should be named "ocp4_workload_sustainable_computing_variable".
#
# You can override the defaults as parameters to the Ansible run that runs
# your workload.
ocp4_workload_sustainable_computing_operator_channel: alpha

ocp4_workload_sustainable_computing_variable_1: "value 1"
ocp4_workload_sustainable_computing_variable_2: "value 2"
ocp4_workload_sustainable_computing_user_info: "This is the OCP4 Example Workload"
ocp4_workload_sustainable_computing_namespace: "ocp4-workload-example-{{ ocp_username }}"
