---
become_override: false
ocp_username: admin
silent: false

# If your workload needs customization options provide variables to be used.
# Variable names must be prefixed by the role name "<role name>_<variable>".
# So because this example workload is called "ocp4_workload_example" the variables
# should be named "ocp4_workload_sustainable_computing_variable".
#

ocp4_workload_sustainable_computing_operator_channel: alpha
