---
- name: Import default destroy playbook
  import_playbook: ../../cloud_providers/{{cloud_provider}}_destroy_env.yml

- name: Delete VMs on VMWare
  hosts: localhost
  connection: local
  become: false
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"

    - name: Create private key
      copy:
        dest: "/tmp/roadshow.pem"
        content: "{{ roadshow_private_key }}"
        mode: 0600

    - name: Request rhpdspoolhandler to for ID
      ansible.builtin.uri:
        url: "{{ roadshow_handler_url }}/roadshowrelease/{{ env_type }}{{ guid }}?code={{ roadshow_handler_code }}"
        status_code: [200, 400]
      register: r_request

    - name: Remove VMs and user if status_code is 400
      set_fact:
        r_request_status: "{{ r_request.status }}"

    - name: Add RHV host to inventory
      ansible.builtin.add_host:
        groupname: jumphost
        name: "jumphost"
        ansible_ssh_host: "{{ roadshow_jumphost }}"
        ansible_ssh_user: root
        ansible_ssh_private_key_file: /tmp/roadshow.pem

- name: Connect to a jumphost to perform operations
  hosts: jumphost
  tasks:
    - debug:
        msg: "{{ hostvars['localhost'] }}"
    - name: Destroy webapp VMs
      ansible.builtin.include_tasks: vcenter-remove-webapp-vms.yml
      when: hostvars['localhost']['r_request_status'] == "400"

    - name: Remove access
      ansible.builtin.include_tasks: vcenter-remove_access.yml
      when: hostvars['localhost']['r_request_status'] == "400"

- name: Remove jumphost from inventory
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - meta: refresh_inventory
