---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"

    - name: Request rhpdspoolhandler to for ID
      ansible.builtin.uri:
        url: "{{ roadshow_handler_url }}/roadshowrequest/{{ env_type }}{{ guid }}}?code={{ roadshow_handler_code }}"
      register: r_request

    - name: Set roadshow_id fact
      set_fact:
        roadshow_id: "{{ r_request.output }}"
