---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"
    - name: Create a VMs in vSphere and assign permissions
      when: cloud_provider == 'equnix_metal' # TODO
      block:
        - name: Create webapp VMs
          ansible.builtin.include_tasks: vcenter-setup-webapp-vms.yml

        - name: Create user on IPA and assign permissions on vSphere
          ansible.builtin.include_tasks: vcenter-setup-user.yml


