- name: Remove the VMs
  register: r_vmc_instances
  community.vmware.vmware_guest:
    folder: "/Workloads/{{env_type}}-{{ guid }}"
    name: "{{ item }}"
    state: "absent"
  loop:
    - haproxy
    - winweb01
    - winweb02
    - database

- name: Delete folder for the project
  community.vmware.vcenter_folder:
    folder_name: "{{ env_type }}-{{ guid }}"
    parent_folder: "Workloads"
    folder_type: vm
    state: absent

