apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
<<<<<<< HEAD:ansible/configs/migrating-to-ocpvirt/files/htpasswd.yaml
        name: htpass-secret
=======
        name: htpasswd
>>>>>>> 6ac4bc0c57ee65c726a3aee907e778de42d5213c:ansible/roles_ocp_workloads/ocp4_workload_authentication/files/oauth-htpasswd.yaml
