- name: Create AAP Operator Argocd Application
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      validate_certs: False
  vars:
    ocp4_workload_gitops_aap_operator_name: ansible-automation-platform
    ocp4_workload_gitops_aap_operator_namespace: "{{ env_type }}-{{ guid }}"
    ocp4_workload_gitops_aap_operator_repo: "{{ ocp4_workload_gitops_aap_repo }}"
    ocp4_workload_gitops_aap_operator_repo_tag: main
    ocp4_workload_gitops_aap_operator_repo_path: operator/base
    # Default source git repository
    ocp4_workload_gitops_aap_repo: https://github.com/redhat-gpte-devopsautomation/aap2-gitops

    # -----------------------------------------------------------------
    # Ansible Automation Controller
    # -----------------------------------------------------------------
    # Enable to install controller
    ocp4_workload_gitops_aap_install_controller: true

    # Single User Controller
    ocp4_workload_gitops_aap_controller_name: controller
    ocp4_workload_gitops_aap_controller_namespace: "{{ env_type }}-{{ guid }}"
    ocp4_workload_gitops_aap_controller_repo: "{{ ocp4_workload_gitops_aap_repo }}"
    ocp4_workload_gitops_aap_controller_repo_tag: cnv
    ocp4_workload_gitops_aap_controller_repo_path: controller/base

    # -----------------------------------------------------------------
    # Ansible Automation Hub
    # -----------------------------------------------------------------
    # Enable to install hub
    ocp4_workload_gitops_aap_install_hub: false

    # Single User Hub
    ocp4_workload_gitops_aap_hub_name: hub
    ocp4_workload_gitops_aap_hub_namespace: "{{ env_type }}-{{ guid }}"
    ocp4_workload_gitops_aap_hub_repo: "{{ ocp4_workload_gitops_aap_repo }}"
    ocp4_workload_gitops_aap_hub_repo_tag: main
    ocp4_workload_gitops_aap_hub_repo_path: hub/base

  block:
    - name: Create AAP Operator Argocd Application
      k8s:
        state: present
        definition: "{{ lookup('template',  'aap-operator.yaml.j2' ) | from_yaml }}"

    - name: Deploy Automation controller
      when: ocp4_workload_gitops_aap_install_controller | bool
      block:
      - name: single user controller
        include_tasks: single_user_controller.yml

      - name: Pause for 5 minutes for AC to be ready
        pause:
          minutes: 5

    - name: Deploy Automation Hub
      when: ocp4_workload_gitops_aap_install_hub | bool
      block:
      - name: single user hub
        include_tasks: single_user_hub.yml

    - name: Openshift Gitops server info
      include_tasks: argocd_info.yml

- name: Generate list of User IDs
  set_fact:
    users: "{{ lookup('sequence', 'start=1 end=1', wantlist=true) | map('int') | list }}"
- debug:
    var: automation_controller_config_multiple_controllers_dictionary
- include_role: 
    name: automation-controller-config

