- name: Create ArgoCD instance and the Application
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      validate_certs: False
  block:
    - name: Create ArgoCD instance
      k8s:
        definition: "{{ lookup('template', './argocd.yaml.j2') | from_yaml }}"

    - name: Check if Deployment finished
      k8s_info:
        api_version: v1
        kind: Deployment
        name: "{{ item }}"
        namespace: "{{ env_type }}-{{ guid }}"
      register: deployment_status
      until: (deployment_status.resources[0].status.readyReplicas | default(0) == 1)
      retries: 10
      delay: 20
      loop:
        - "{{ guid }}-argocd-redis"
        - "{{ guid }}-argocd-repo-server"
        - "{{ guid }}-argocd-server"
