- name: Create Gitea instance 
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      validate_certs: False
  vars:
    ocp4_workload_gitea_operator_user_number: "{{ num_users }}"
    ocp4_workload_gitea_operator_gitea_volume_storage_class: ''
    ocp4_workload_gitea_operator_postgresql_volume_storage_class: ''
    ocp4_workload_gitea_operator_admin_password_length: 16
    ocp4_workload_gitea_operator_user_number: "{{ num_users }}"
    ocp4_workload_gitea_operator_generate_user_format: user1
    ocp4_workload_gitea_operator_user_password_length: 16
    ocp4_workload_gitea_operator_user_email_domain: opentlc.com

  block:
    - name: Create Gitea instance
      k8s:
        state: present
        definition: "{{ lookup('template', 'gitea.yaml.j2' ) | from_yaml }}"
    - name: Wait for Gitea route to be available
      k8s_info:
        api_version: gitea.pfe.rhpds.com/v1
        kind: Gitea
        name: "{{ ocp4_workload_gitea_operator_name }}"
        namespace: "{{ env_type }}-{{ guid }}"
      register: r_gitea
      until: r_gitea.resources[0].status.giteaRoute is defined
      retries: 90
      delay: 10

    - name: Set gitea route variable
      set_fact:
        _ocp4_workload_gitea_operator_gitea_route: "{{ r_gitea.resources[0].status.giteaRoute }}"

    - name: Print the Gitea route
      agnosticd_user_info:
        msg: "You can access Gitea via the URL {{ _ocp4_workload_gitea_operator_gitea_route }}"
        data:
          gitea_console_url: "{{ _ocp4_workload_gitea_operator_gitea_route }}"

    - name: Wait for Gitea admin password to be set
      when: ocp4_workload_gitea_operator_create_admin | bool
      block:
      - name: Wait for Gitea admin password to be set
        k8s_info:
          api_version: gitea.pfe.rhpds.com/v1
          kind: Gitea
          name: "{{ ocp4_workload_gitea_operator_name }}"
          namespace: "{{ env_type }}-{{ guid }}"
        register: r_gitea_admin_password
        until:
        - r_gitea_admin_password.resources[0].status.adminSetupComplete is defined
        - r_gitea_admin_password.resources[0].status.adminSetupComplete | bool
        retries: 60
        delay: 10

      - name: Print admin credentials if admin was created
        when: ocp4_workload_gitea_operator_create_admin | bool
        agnosticd_user_info:
          msg: "{{ item }}"
          data:
            gitea_admin_username: "{{ ocp4_workload_gitea_operator_admin_user }}"
            gitea_admin_password: "{{ r_gitea_admin_password.resources[0].status.adminPassword }}"
        loop:
        - "The Gitea admin username is '{{ ocp4_workload_gitea_operator_admin_user }}'."
        - "The Gitea admin password is '{{ r_gitea_admin_password.resources[0].status.adminPassword }}'."

    - name: Wait for Gitea user setup to be complete
      when: ocp4_workload_gitea_operator_create_users | bool
      block:
      - name: Wait for Gitea users to be set up
        k8s_info:
          api_version: gitea.pfe.rhpds.com/v1
          kind: Gitea
          name: "{{ ocp4_workload_gitea_operator_name }}"
          namespace: "{{ env_type }}-{{ guid }}"
        register: r_gitea_user_setup_complete
        until:
        - r_gitea_user_setup_complete.resources[0].status.userSetupComplete is defined
        - r_gitea_user_setup_complete.resources[0].status.userSetupComplete | bool
        retries: 120
        delay: 20

      - name: Print the user details if a single user was created
        agnosticd_user_info:
          msg: >-
            A Gitea user '{{ ocp4_workload_gitea_operator_generate_user_format }}' was created, with the password
            '{{ r_gitea_user_setup_complete.resources[0].status.userPassword }}'

      - name: Print user details per created user
        when: ocp4_workload_gitea_operator_user_number | int > 1
        agnosticd_user_info:
          msg: "{{ ocp4_workload_gitea_operator_generate_user_format | format(n) }}"
          data:
            gitea_user: "{{ ocp4_workload_gitea_operator_generate_user_format | format(n) }}"
            gitea_password: "{{ ocp4_workload_gitea_operator_user_password }}"
            gitea_console_url: "{{ _ocp4_workload_gitea_operator_gitea_route }}"
        loop: "{{ range(1, 1 + ocp4_workload_gitea_operator_user_number | int) | list }}"
        loop_control:
          loop_var: n

      - name: Wait for repository migration to be complete
        when: ocp4_workload_gitea_operator_migrate_repositories | bool
        block:
        - name: Wait for Gitea repository migration to be complete
          k8s_info:
            api_version: gitea.pfe.rhpds.com/v1
            kind: Gitea
            name: "{{ ocp4_workload_gitea_operator_name }}"
            namespace: "{{ env_type }}-{{ guid }}"
          register: r_gitea_repo_setup_complete
          until:
          - r_gitea_repo_setup_complete.resources[0].status.repoMigrationComplete is defined
          - r_gitea_repo_setup_complete.resources[0].status.repoMigrationComplete | bool
          retries: 60
          delay: 10

        - name: Print the repositories that were migrated
          agnosticd_user_info:
            msg: "{{ item }}"
          loop:
          - "The following repositories were migrated for the created users:"
          - "{{ ocp4_workload_gitea_operator_repositories_list | join(', ', attribute='repo') }}"

