---
- name: Step 004 Software
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step004
    - deploy_software
  tasks:
    - include_tasks: authentication.yaml 
    - include_tasks: argocd.yaml
    - include_tasks: gitea.yaml
    - include_tasks: aap2.yaml
