---
################################################################################
### OpenShift CNV Environment variables
################################################################################

cloud_provider: openshift_cnv
ansible_user: cloud-user
remote_user: cloud-user
openshift_cnv_project_name: "{{ env_type }}-{{ guid }}"


# Default instance resources
__instance_type: 2c2g30d
__instance_memory: "4G"
__instance_cores: 2
__instance_image_size: 20G


# Default Image
__image: rhel-server-7.7-update-2

# Environment Instances
instances:
  - name: "bastion"
    count: 1
    unique: true
    image: "{{ bastion_instance_image | default(__image) }}"
    memory: "{{ bastion_instance_memory | default(__instance_memory) }} "
    cores: "{{ bastion_instance_core | default(__instance_cores) }}"
    image_size: "{{ bastion_instance_image_size | default(__instance_image_size) }}"

    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"

  - name: "frontend"
    count: "{{ frontend_instance_count | default(1) }}"
    image: "{{ frontend_instance_image | default(__image) }}"
    memory: "{{ frontend_instance_memory | default(__instance_memory) }}"
    cores: "{{ frontend_instance_core | default(__instance_cores) }}"
    image_size: "{{ frontend_instance_image_size | default(__instance_image_size) }}"
    services:
        - port: 80 
          protocol: TCP
          targetPort: 80
          name: frontend-http
    routes:
        - name: frontend1
          service: frontend-http
          targetPort: 80
          tls: False

    tags:
      - key: "AnsibleGroup"
        value: "frontends"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"

  - name: "app"
    count: "{{ app_instance_count | default(2) }}"
    image: "{{ app_instance_image | default(__image) }}"
    memory: "{{ app_instance_memory | default(__instance_memory) }}"
    cores: "{{ app_instance_core | default(__instance_cores) }}"
    image_size: "{{ app_instance_image_size | default(__instance_image_size) }}"


    tags:
      - key: "AnsibleGroup"
        value: "apps"
      - key: "ostype"
        value: "rhel"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"

  - name: "appdb"
    count: "{{ appdb_instance_count | default(1) }}"
    image: "{{ appdb_instance_image | default(__image) }}"
    memory: "{{ appdb_instance_memory | default(__instance_memory) }}"
    cores: "{{ appdb_instance_core | default(__instance_cores) }} "
    image_size: "{{ appdb_instance_image_size | default(__instance_image_size) }}"
    tags:
      - key: "AnsibleGroup"
        value: "appdbs"
      - key: "ostype"
        value: "rhel"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"


