---
openshift_cnv_project_name: "{{ env_type }}-{{ guid }}"

# Defaults for devices
#openshift_cnv_default_os: centos_8

# SSH keys
openshift_cnv_ssh_key_path: "{{ output_dir }}/{{ guid }}_id_rsa"
openshift_cnv_ssh_pub_key_path: "{{ output_dir }}/{{ guid }}_id_rsa.pub"

# Naming of instances
openshift_cnv_instance_numeration: '%d'

# Delete device retry
openshift_cnv_delete_retries: 20
openshift_cnv_delete_delay: 60
