---
- name: Step 005 Post Software
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
  - step005
  - post_software
  environment:
    K8S_AUTH_VERIFY_SSL: false
    K8S_AUTH_HOST: "{{ prp_ocp_argo.openshift_api_server_url }}"
    K8S_AUTH_USERNAME: "{{ prp_ocp_argo.openshift_cluster_admin_username }}"
    K8S_AUTH_PASSWORD: "{{ prp_ocp_argo.openshift_cluster_admin_password }}"
  tasks:

  - name: Entering the prp-binder post_software.yml
    debug:
      msg:
      - Entering the prp-binder post_software.yml

  - name: Log in (obtain access token)
    community.okd.openshift_auth:
      validate_certs: false
      username: "{{ prp_ocp_argo.openshift_cluster_admin_username }}"
      password: "{{ prp_ocp_argo.openshift_cluster_admin_password }}"
      host: "{{ prp_ocp_argo.openshift_cluster_admin_username }}"
    register: _auth_results

  - name: Access OpenShift
    ansible.builtin.import_role:
      name: ocp4_workload_gitops_bootstrap
    environment:
      K8S_AUTH_VERIFY_SSL: false
      K8S_AUTH_HOST: "{{ prp_ocp_argo.openshift_api_server_url }}"
      K8S_AUTH_USERNAME: "{{ prp_ocp_argo.openshift_cluster_admin_username }}"
      K8S_AUTH_API_KEY: "{{ _auth_results.openshift_auth.api_key }}"

  - name: Print string expected by Cloudforms
    debug:
      msg: "Post-Software checks completed successfully"

  - name: Exiting the prp-binder post_software.yml
    debug:
      msg:
      - Exiting the prp-binder post_software.yml
...
