---
- include_role:
    name: infra-cloud-tags
  when: cloud_tags_final is not defined

# BEGIN DELETEME AFTER SUMMIT
- set_fact:
    equinix_metal_facilities: [ch3,dc10,dc13,sv15,da11,sv15]
    available_equinix_metal_facilities: []
- equinix.metal.capacity_info:
    auth_token: "{{ equinix_metal_api_token }}"
  register: r_capacity_info
- name: Filter locations
  set_fact:
    available_equinix_metal_facilities: "{{ available_equinix_metal_facilities + [item['key']] }}"
  when: item.key in equinix_metal_facilities and item['value']['m3.large.x86']  != "unavailable"
  loop: "{{ r_capacity_info | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
- set_fact:
    location: "{{available_equinix_metal_facilities | random }}"
# END DELETEME AFTER SUMMIT

# https://metal.equinix.com/developers/api/devices/
- name: Create Devices
  register: r_equinix_metal_devices
  loop: "{{ instances }}"
  loop_control:
    loop_var: _instance
    label: _instance.name
  vars:
  equinix.metal.device:
    wait_for_public_IPv: 4
    auth_token: "{{ equinix_metal_api_token }}"
    project_id: "{{ equinix_metal_project_id }}"
    hostnames: >-
      {{ _instance.name }}
      {%- if _instance.count | int > 1 -%}
      {{ equinix_metal_instance_numeration }}
      {%- endif -%}
    count: "{{ _instance.count }}"
    operating_system: "{{ _instance.os | default(equinix_metal_default_os) }}"
    plan: "{{ _instance.type }}"
    facility: "{{ available_equinix_metal_facilities | random }}"
    tags: >-
      {{ cloud_tags_final
      | combine(_instance.tags | ec2_tags_to_dict)
      | dict_to_equinix_metal_tags }}
    user_data: |
      #cloud-config
      ssh_authorized_keys:
        - {{ lookup('file', equinix_metal_ssh_pub_key_path ) }}
    retries: 5
    delay: 30
    until: r_equinix_metal_devices is success

- debug:
    var: r_equinix_metal_devices
    verbosity: 3
