# vim: ft=yaml
---
- name: Install Operator and configure external Ceph
  block:
    - name: Set up ODF operator
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template',  item ) | from_yaml }}"
      loop: [odf-ns.yaml, odf-og.yaml, odf-sub.yaml.j2]

    - name: Set up StorageCluster
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template',  item) | from_yaml }}"
      register: r_storagecluster
      until: r_storagecluster is success
      retries: 30
      delay: 30
      loop: [secret.yaml.j2, storageclass.yaml.j2, storagecluster.yaml.j2]

- name: Deploy Image Regsistry to external ODF
  when: ocp4_workload_external_odf_registry_move_enable
  block:
    - name: Create PVC for image registry
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template',  'pvc-imageregistry.yaml') | from_yaml }}"
      register: r_pvc
      until: r_pvc is success
      retries: 30
      delay: 30

    - name: Configure registry
      kubernetes.core.k8s:
        state: patched
        api_version: imageregistry.operator.openshift.io/v1
        kind: Config
        name: cluster
        merge_type: merge
        definition:
          spec:
            rolloutStrategy: Recreate
            replicas: 1
            storage:
              pvc:
                claim: pvc-image-registry
            managementState: Managed

    - name: Enable ODF UI plugin
      kubernetes.core.k8s_json_patch:
        api_version: operator.openshift.io/v1
        kind: Console
        namespace: openshift-storage
        name: cluster
        patch:
          - op: add
            path: /spec/plugins
            value: [odf-console]
