---

- name: Set CUDA related vars for all users
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      CUDA_HOME={{ setup_instructlab_cuda_home }}
      LD_LIBRARY_PATH={{ setup_instructlab_cuda_lib_path }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: true

- name: Set CUDA related vars etc in .bashrc
  ansible.builtin.blockinfile:
    path: "/home/{{ setup_instructlab_user }}/.bashrc"
    block: |
      export CUDA_HOME={{ setup_instructlab_cuda_home }}
      export LD_LIBRARY_PATH={{ setup_instructlab_cuda_lib_path }}
      export PATH=$PATH:/usr/local/cuda/bin
      {% if not setup_instructlab_summit2024_mode %}
      echo "Welcome to the InstructLab VM"
      echo
      echo "- To get started see https://github.com/instructlab"
      echo "- To chat: ilab chat"
      echo
      {% endif %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: true
  become_user: "{{ setup_instructlab_user | default('instruct') }}"
