---
######################### Deploy OpenShift using Assisted Installer

- name: Step 004.2 - Install OpenShift
  hosts: bastions
  gather_facts: false
  become: false
  tags:
    - step004
    - step004.2
  tasks:
    - name: Call Role to install OpenShift
      when: install_ocp4 | d(True) | bool
      include_role:
        name: host-ocp4-assisted-installer
