---
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  creationTimestamp: null
  name: hcp-{{ guid }}
  namespace: {{ namespace }}
spec:
  autoscaling: {}
  configuration: {}
  controllerAvailabilityPolicy: SingleReplica
  dns:
    baseDomain: {{ cluster_dns_zone }}
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
        type: PersistentVolume
    managementType: Managed
  fips: false
  infraID: hcp-{{ guid }}-{{ lookup('community.general.random_string', upper=false, numbers=false, special=false) }}
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  olmCatalogPlacement: management
  platform:
    kubevirt:
      baseDomainPassthrough: true
      credentials:
        infraKubeConfigSecret:
          key: kubeconfig
          name: hcp-{{ guid }}-infra-credentials
        infraNamespace: {{ namespace }}
    type: KubeVirt
  pullSecret:
    name: hcp-{{ guid }}-pull-secret
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.16.10-x86_64
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: OVNSbDb
    servicePublishingStrategy:
      type: Route
  sshKey: {}
status:
  controlPlaneEndpoint:
    host: ""
    port: 0
