---
- name: Debug OpenShift CNV Instances fact
  debug:
    var: r_openshift_cnv_instances
    verbosity: 2

# Find the bastion
- name: Find the bastion in this batch of hosts
  loop: "{{ r_openshift_cnv_instances | list }}"
  set_fact:
    local_bastion: "{{ item.kubevirt_vm.metadata.name }}"
  when:
    - '"bastions" in item.kubevirt_vm.metadata.annotations.AnsibleGroup|default("")'
  ignore_errors: true

- name: Expose bastion externally
  register: r_expose_bastion
  k8s:
    host: "{{ openshift_cnv_api_uri }}"
    api_key: "{{ openshift_cnv_api_key }}"
    validate_certs: False
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ local_bastion }}-ssh"
        namespace: "{{ openshift_cnv_project_name }}"
      spec:
        ports:
        - port: 22
          protocol: TCP
          targetPort: 22
        selector:
          vm.cnv.io/name: "{{ local_bastion }}"
        sessionAffinity: None
        type: NodePort

- name: Debug OpenShift CNV Instances fact
  debug:
    var: r_openshift_cnv_instances
    verbosity: 2

- name: Create inventory (add_host)
  loop: "{{ r_openshift_cnv_instances | list }}"
  add_host:
    name: "{{ item.kubevirt_vm.metadata.name }}"
    ansible_ssh_host: "{{ item.kubevirt_vm.metadata.name }}"
    ansible_ssh_port: "{{ r_expose_bastion.result.spec.ports.0.nodePort }}"
    private_ip_address: "{{ item.kubevirt_vm.metadata.name }}"
    public_ip_address: "ssh.{{ openshift_cnv_apps_domain }}"
    groups: "{{ item.kubevirt_vm.metadata.annotations.AnsibleGroup|default(omit) }}"
    bastion: "{{ local_bastion | default('') }}"
    bastion_ssh_port: "{{ r_expose_bastion.result.spec.ports.0.nodePort }}"
    isolated:  "{{ item.kubevirt_vm.metadata.annotations.isolated | default(false) }}"
  when: "{{ item.kubevirt_vm.metadata.annotations.managed|default(True)|bool != False}}"

- name: Get a list of VMIs
  k8s_info:
    host: "{{ openshift_cnv_api_uri }}"
    api_key: "{{ openshift_cnv_api_key }}"
    validate_certs: False
    kind: VirtualMachineInstance
    namespace: "{{ openshift_cnv_project_name }}"
  register: r_vmi_list

- name: Set the variable r_vmi_list as a fact in localhost
  set_fact:
    r_vmi_list: "{{ r_vmi_list }}"
    



