---

- name: Get a list of VMs
  k8s_info:
    host: "{{ openshift_cnv_api_uri }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: False
    kind: VirtualMachine
    namespace: "{{ openshift_cnv_project_name }}"
  register: r_openshift_cnv_instances
  when: r_openshift_cnv_instances is not defined


- name: Debug OpenShift CNV Instances fact
  debug:
    var: r_openshift_cnv_instances

# Find the bastion
- name: Find the bastion in this batch of hosts
  loop: "{{ r_openshift_cnv_instances.resources | list }}"
  set_fact:
    local_bastion: "{{ item.metadata.name }}"
  when:
    - '"result" in item and "bastions" in item.metadata.annotations.AnsibleGroup|default("")'
  ignore_errors: true

- name: Expose bastion externally
  register: r_expose_bastion
  when: local_bastion|default(False)
  kubernetes.core.k8s:
    host: "{{ openshift_cnv_api_uri }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: False
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ local_bastion }}-ssh"
        namespace: "{{ openshift_cnv_project_name }}"
      spec:
        ports:
        - port: 22
          protocol: TCP
          targetPort: 22
        selector:
          vm.cnv.io/name: "{{ local_bastion }}"
        sessionAffinity: None
        type: NodePort

- name: Debug OpenShift CNV Instances fact
  debug:
    var: r_openshift_cnv_instances
    verbosity: 2

- name: Create inventory (add_host)
  loop: "{{ r_openshift_cnv_instances.resources | list }}"
  add_host:
    name: "{{ item.metadata.name }}"
    shortname: "{{ item.metadata.name }}"
    ansible_ssh_host: "{{ item.metadata.name }}"
    ssh_port: "{{ r_expose_bastion.spec.ports.0.nodePort|default(omit) }}"
    private_ip_address: "{{ item.metadata.name }}"
    public_ip_address: "{{ openshift_cnv_ssh_address }}"
    groups: "{{ item.metadata.annotations.AnsibleGroup }}"
    bastion: "{{ local_bastion | default('') }}"
    bastion_ssh_port: "{{ r_expose_bastion.spec.ports.0.nodePort|default(omit) }}"
    isolated: "{{ item.metadata.annotations.isolated | default(false) }}"
  when: "item.metadata.annotations.managed|default(True)|bool != False"
