---
#- include: authentication.yaml
- name: Log in (obtain access token)
  community.okd.k8s_auth:
    username: "{{ openshift_cnv_username }}"
    password: "{{ openshift_cnv_password }}"
    host: "{{ openshift_cnv_api_uri }}"
  register: k8s_auth_results
- block:
    - include_tasks: create_inventory.yaml
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      validate_certs: False
