---
#- include: authentication.yaml
- block:
    - include_tasks: create_inventory.yaml
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ openshift_cnv_api_key }}"
      validate_certs: False
