---
# Workloads are being run on bastion.
# This enables using the k8s module in the workload.
# openshift python module is installed for Python3
- name: Install workloads
  hosts: localhost
  gather_facts: false
  run_once: true
  become: false
  tasks:
  - name: Set kube config directory
    set_fact:
      kubeconfigdir: "{{ output_dir }}/.kube"

  - name: Set kube config file path
    set_fact:
      kubeconfig: "{{ kubeconfigdir }}/config"

  - name: Make sure .kube directory exists
    ansible.builtin.file:
      state: directory
      path: "{{ kubeconfigdir }}"
      mode: 0700

  - name: Login to the resulting ARO cluster as kubeadmin
    ansible.builtin.command: >-
      oc login {{ az_aro4_public_api_url }} -u kubeadmin -p {{ az_aro4_kubeadmin_password.stdout }} --kubeconfig {{ kubeconfig }} --insecure-skip-tls-verify
    register: r_cluster_login
    retries: 6
    delay: 60
    until: r_cluster_login is success

  - name: Install ocp-student-workloads
    when:
    - user_count | default(0) | int > 0
    - student_workloads | default("") | length > 0
    tags:
    - student_workloads
    block:
    - name: Check if authentication mechanism is set to htpasswd
      when: install_idm | default("") != "htpasswd"
      fail:
        msg: Authentication Mechanism must be htpasswd

    - name: Generate list of User IDs
      set_fact:
        users: "{{ lookup('sequence', 'start=1 end={{ user_count|int }}', wantlist=true) | map('int') | list }}"

    - name: Deploy ocp-student-workloads for each user ID
      include_role:
        name: "{{ workload_loop_var[1] }}"
      vars:
        ocp_username: "user{{ workload_loop_var[0] }}"
        become_override: true
        ACTION: "provision"
      loop: "{{ users | product(student_workloads) | list }}"
      loop_control:
        loop_var: workload_loop_var
