---
- hosts: localhost
  gather_facts: false
  tasks:
    - add_host:
        hostname: citrixgw
        ansible_host: 192.168.3.5
        ansible_password: "{{ vdi_password }}"
        ansible_user: nsroot
        ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ ocp4_aio_ssh_key_path }} -A -o StrictHostKeyChecking=no  -W %h:%p root@{{  hostvars["hypervisor"]["public_ip_address"] }}"  -o StrictHostKeyChecking=no'

- hosts: citrixgw
  gather_facts: false
  tasks:
    - name: Configure appliance
      raw: "{{ item }}"
      loop:
        - "shell echo '{{ lookup('file', output_dir + '/cert.pem') }}' > /flash/nsconfig/ssl/cert.pem"
        - "shell echo '{{ lookup('file', output_dir + '/fullchain.pem') }}' > /flash/nsconfig/ssl/fullchain.pem"
        - "shell echo '{{ lookup('file', output_dir + '/privkey.pem') }}' > /flash/nsconfig/ssl/privkey.pem"
        - "update ssl certKey cert.pem_CERT_KEY -cert fullchain.pem -key privkey.pem -noDomainCheck"
        - "set vpn vserver _XD_192.168.3.8_443 -vserverFqdn citrixgw.{{ guid }}.dynamic.opentlc.com"


