---
- name: Forward port 443 to citrixgw:443 with iptables
  ansible.builtin.iptables:
    action: insert
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination: "{{ hostvars['localhost']['citrixgw_public_ip'] }}"
    destination_port: "443"
    jump: DNAT
    to_destination: 192.168.3.8:443

- name: Get token from iam.cloud.ibm.com
  register: r_iam_token
  uri:
    url: "https://iam.cloud.ibm.com/oidc/token"
    method: POST
    headers:
      Accept: 'application/json'
      Content-Type: 'application/x-www-form-urlencoded'
    body_format: form-urlencoded
    body:
      apikey: "{{ ibmcos_api_key }}"
      response_type: "cloud_iam"
      grant_type: "urn:ibm:params:oauth:grant-type:apikey"

- name: Save access token
  set_fact:
    ibmcos_access_token: "{{ r_iam_token.json.access_token }}"


- name: Download Citrix GW qcow2 file
  ansible.builtin.get_url:
    url: "{{ vdi_import_url }}/NSVPX-KVM-13.1-49.13_nc_64.qcow2"
    dest: "/var/lib/libvirt/images/NSVPX-KVM-13.1-49.13_nc_64.qcow2"
    headers:
      Authorization: "bearer {{ ibmcos_access_token }}"

- name: Download Citrix GW definition file
  ansible.builtin.get_url:
    url: "{{ vdi_import_url }}/NetScaler-VPX.xml"
    dest: "/root/NetScaler-VPX.xml"
    headers:
      Authorization: "bearer {{ ibmcos_access_token }}"

- name: Define the Citrix GW and start it
  command: "{{ item }}"
  loop:
    - virsh define /root/NetScaler-VPX.xml
    - virsh start NetScaler-VPX
