---
- set_fact:
    equinix_metal_project_id: "{{ lookup('agnosticd_user_data', 'equinix_metal_project_id') }}"

- name: Get device information in the project
  equinix.metal.device_info:
    auth_token: "{{ equinix_metal_api_token }}"
    project_id: "{{ equinix_metal_project_id }}"
  register: r_device_info

- name: Reserve a public IP
  equinix.cloud.metal_reserved_ip_block:
    project_id: "{{ equinix_metal_project_id }}"
    type: public_ipv4
    quantity: 1
    metro: "dc"
  register: r_metal_reserved_ip_block

- name: Assign available IP
  equinix.cloud.metal_ip_assignment:
    device_id: "{{ r_device_info.id }}"
    address: "{{ r_metal_reserved_ip_block.network }}"
  register: r_metal_ip_assignment
