---
- hosts: localhost
  gather_facts: false
  tasks:
    - add_host:
        hostname: citrixgw
        ansible_host: 192.168.3.5
        ansible_password: "{{ vdi_password }}"
        ansible_user: nsroot

    - add_host:
        hostname: citrix
        ansible_host: 192.168.3.10
        ansible_password: "{{ vdi_password }}"
        ansible_connection: winrm
        ansible_user: Administrator@win.example.com
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: ntlm

- hosts: citrixgw
  gather_facts: false
  tasks:
    - name: Configure appliance
      raw: "{{ item }}"
      loop:
        - "shell echo '{{ lookup('file', output_dir + '/fullchain.pem') }}' > /flash/nsconfig/ssl/fullchain.pem"
        - "shell echo '{{ lookup('file', output_dir + '/privkey.pem') }}' > /flash/nsconfig/ssl/privkey.pem"
        - "update ssl certKey cert.pem_CERT_KEY -cert fullchain.pem -key privkey.pem -noDomainCheck"
        - "set vpn vserver _XD_192.168.3.8_443 -vserverFqdn citrixgw.{{ guid }}.dynamic.opentlc.com"

- hosts: citrix
  gather_facts: false
  tasks:
    - wait_for_connection:
        delay: 60
        timeout: 600
    - include_tasks: configure_citrix_storefront.yaml
