---
- set_fact:
    equinix_metal_project_id: "{{ lookup('agnosticd_user_data', 'equinix_metal_project_id') }}"

- name: Get device information in the project
  equinix.metal.device_info:
    auth_token: "{{ equinix_metal_api_token }}"
    project_id: "{{ equinix_metal_project_id }}"
  register: r_device_info

- name: Create a Public IP
  uri:
    url: "https://api.equinix.com/metal/v1/projects/{{ equinix_metal_project_id }}/ips"
    method: POST
    headers:
      X-Auth-Token: "{{ equinix_metal_api_token }}"
    body:
      type: "public_ipv4"
      quantity: "1"
      metro: "dc"
    body_format: json
    status_code: 201
  register: r_public_ip

- debug:
    msg: "{{ r_public_ip.json.network }}"

- name: Assign available IP
  equinix.metal.ip_subnet:
    auth_token: "{{ equinix_metal_api_token }}"
    device_id: "{{ r_device_info.devices[0].id }}"
    cidr: "{{ r_public_ip.json.network }}/{{ r_public_ip.json.cidr }}"
  register: r_metal_ip_assignment
