---
- hosts: localhost
  gather_facts: false
  tasks:
    - add_host:
        hostname: citrix
        ansible_host: 192.168.3.10
        ansible_password: "{{ vdi_password }}"
        ansible_connection: winrm
        ansible_user: Administrator@win.example.com
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: ntlm
        ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ ocp4_aio_ssh_key_path }} -A -o StrictHostKeyChecking=no  -W %h:%p root@{{  hostvars["hypervisor"]["public_ip_address"] }}"  -o StrictHostKeyChecking=no'

- hosts: citrix
  gather_facts: false
  tasks:
    - wait_for_connection:
        delay: 60
        timeout: 600
    - include_tasks: configure_citrix_storefront_tasks.yaml
