---
- name: Forward port 443 to citrixgw:443 with iptables
  ansible.builtin.iptables:
    action: insert
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination: "{{ hostvars['localhost']['citrixgw_public_ip'] }}"
    destination_port: "9001"
    jump: DNAT
    to_destination: 192.168.3.5:443

- name: Download Citrix GW qcow2 file
  ansible.builtin.get_url:
    url: "{{ vdi_import_url }}/NSVPX-KVM-13.1-49.13_nc_64.qcow2"
    dest: "/var/lib/libvirt/images/NSVPX-KVM-13.1-49.13_nc_64.qcow2"

- name: Download Citrix GW definition file
  ansible.builtin.get_url:
    url: "{{ vdi_import_url }}/NetScaler-VPX.xml"
    dest: "/root/NetScaler-VPX.xml"

- name: Define the Citrix GW and start it
  command: "{{ item }}"
  loop:
    - virsh define /root/NetScaler-VPX.xml
    - virsh start NetScaler-VPX
