---
- name: Get token from iam.cloud.ibm.com
  register: r_iam_token
  uri:
    url: "https://iam.cloud.ibm.com/oidc/token"
    method: POST
    headers:
      Accept: 'application/json'
      Content-Type: 'application/x-www-form-urlencoded'
    body_format: form-urlencoded
    body:
      apikey: "{{ ibmcos_api_key }}"
      response_type: "cloud_iam"
      grant_type: "urn:ibm:params:oauth:grant-type:apikey"

- name: Save access token
  set_fact:
    ibmcos_access_token: "{{ r_iam_token.json.access_token }}"

- name: Download prebuilt VMs for Citrix GW
  ansible.builtin.get_url:
    url: "{{ vdi_import_url }}/{{ item }}"
    dest: "/var/www/html/{{ item }}"
    headers:
      Authorization: "bearer {{ ibmcos_access_token }}"
  loop:
    - citrix.qcow2
    - dc.qcow2
    - rhel9.qcow2
    - win10.qcow2
    - win11.qcow2
    - win11-02.qcow2
