---
- name: Step 005 post software
  hosts: localhost
  gather_facts: false
  become: true
  tags:
    - step005
    - post_software

  tasks:

    - name: "Post-Software tasks Started"
      ansible.builtin.debug:
        msg: "Post-Software tasks Started"

    - name: Save user data
      agnosticd_user_info:
        data:
          cloud_provider: "{{ cloud_provider }}"
          ssh_command: "ssh {{ student_name }}@{{ openshift_cnv_ssh_address }} -p {{ hostvars[groups['bastions'][0]].bastion_ssh_port }}"
          ssh_password: "{{ student_password }}"
          ssh_username: "{{ student_name }}"
          guid: "{{ guid }}"
          targethost: "{{ groups['bastions'][0] | regex_replace('\\..*$') }}.{{ guid }}{{ subdomain_base_suffix }}"
          targetport: "{{ hostvars[groups['bastions'][0]].bastion_ssh_port }}"
          subdomain: "{{ guid }}{{ subdomain_base_suffix }}"
          subdomain_internal: "{{ chomped_zone_internal_dns | default('') }}"
      vars:
        student_name: "{{ student_name }}"
      register: r_user_data


    - name: Output ssh user_info for ec2 based deploys
      when:
        - cloud_provider == "ec2"
      block:
        - name: Set ssh user_info
          agnosticd_user_info:
            msg: "{{ __user_info }}"
          loop:
            - "To Access development node via SSH:"
            - "ssh_command: ssh {{ student_name }}@{{ groups['bastions'][0] | regex_replace('\\..*$') }}.{{ guid }}{{ subdomain_base_suffix }}"
            - "Enter ssh password when prompted: {{ student_password }}"
            - ""
          loop_control:
            loop_var: __user_info

        - name: Save user data
          agnosticd_user_info:
            data:
              cloud_provider: "{{ cloud_provider }}"
              ssh_command: "ssh {{ student_name }}@{{ groups['bastions'][0] | regex_replace('\\..*$') }}.{{ guid }}{{ subdomain_base_suffix }}"
              ssh_password: "{{ student_password }}"
              ssh_username: "{{ student_name }}"
              guid: "{{ guid }}"
              targethost: "{{ groups['bastions'][0] | regex_replace('\\..*$') }}.{{ guid }}{{ subdomain_base_suffix }}"
              subdomain: "{{ guid }}{{ subdomain_base_suffix }}"
              subdomain_internal: "{{ chomped_zone_internal_dns | default('') }}"
          vars:
            student_name: "{{ ansible_service_account_user_name }}"
          register: r_user_data

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:

    - name: "Post-Software checks completed successfully"
      ansible.builtin.debug:
        msg: "Post-Software checks completed successfully"
...
