---
- name: Step 003 Pre Software
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - step004
    - pre_software

  tasks:

    - name: "Step 003 Pre Software"
      ansible.builtin.debug:
        msg: "Step 000 Pre Software"

    - name: Set local ssh key
      when: agd_set_env_authorized_key | default(true) | bool
      ansible.builtin.import_role:
        name: create_ssh_provision_key

- name: Configuring Windows Bastion Host
  hosts: windows
  become: false
  tags:
    - step004
    - bastion_tasks
  vars:
    ansible_user: Administrator
  tasks:
    - name: Include windows-common role
      ansible.builtin.include_role:
        name: windows-common

    - name: Generate host .ssh/config Template
      ansible.builtin.template:
        src: "./files/ssh_config.j2"
        dest: "{{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}"
      delegate_to: localhost
      become: false
      tags:
        - gen_sshconfig_file

    - name: Setup Windows ssh config customization
      block:
        - name: Copy SSH key template to Windows server
          ansible.windows.win_copy:
            src: "{{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}"  # Path to your SSH key template file
            dest: C:\temp\ssh_key.pub                # Destination path on the Windows server
            force: yes                              # Overwrite existing file if it exists

        - name: Create .ssh directory if it doesn't exist
          ansible.windows.win_file:
            path: C:\Users\"{{ windows_user }}"\.ssh   # Path to Administrator's .ssh directory
            state: directory

        - name: Create authorized_keys file if it doesn't exist
          ansible.windows.win_file:
            path: C:\Users\"{{ windows_user }}"\.ssh\authorized_keys   # Path to authorized_keys file
            state: touch

        - name: Add SSH key to Administrator's authorized_keys file
          ansible.windows.win_lineinfile:
            path: C:\Users\"{{ windows_user }}"\.ssh\authorized_keys   # Path to authorized_keys file
            line: "{{ lookup('file', 'C:/temp/ssh_key.pub') }}"  # Add content of SSH key template file

        - name: Generate host .ssh/config Template
          ansible.builtin.template:
            src: "./files/ssh_config.j2"
            dest: "{{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}"
          delegate_to: localhost
          become: false
          tags:
            - gen_sshconfig_file

        - name: copy over host .ssh/config Template
          ansible.builtin.copy:
            src: "{{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}"
            dest: /root/.ssh/config
            owner: root
            group: root
            mode: 0400
          become: true
          tags:
            - copy_sshconfig_file

- name: PreSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - flight_check

  tasks:

    - name: "Pre-Software checks completed successfully"
      ansible.builtin.debug:
        msg: "Pre-Software checks completed successfully"
...
