---
collections:

  - name: amazon.aws
    version: 4.0.0

  - name: ansible.windows
    version: 2.3.0

  - name: chocolatey.chocolatey
    version: 1.5.1

  - name: community.general
    version: 8.1.0

  - name: containers.podman
    version: 1.10.1

...
