---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Configure /etc/hosts for openshift_cnv
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Configure /etc/hosts
      when: cloud_provider == "openshift_cnv"
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          ## Public Network -.example.com ##
          192.168.56.252	workstation.example.com workstation-{{ guid }}.example.com classroom.example.com
          192.168.56.50	ctrl01.example.com
          192.168.56.24	proxy01.example.com
          192.168.56.25	proxy02.example.com
          192.168.56.61	ceph-node01.example.com
          192.168.56.62	ceph-node02.example.com
          192.168.56.63	ceph-node03.example.com
          192.168.56.64	ceph-mon01.example.com
          192.168.56.65	ceph-mon02.example.com
          192.168.56.66	ceph-mon03.example.com
          192.168.56.80   haproxy01.example.com

          ## Admin Network - example.com ##
          172.16.7.252	workstation classroom
          172.16.7.24	proxy01
          172.16.7.25	proxy02
          172.16.7.61	ceph-node01
          172.16.7.62	ceph-node02
          172.16.7.63	ceph-node03
          172.16.7.64	ceph-mon01
          172.16.7.65	ceph-mon02
          172.16.7.66	ceph-mon03
          172.16.7.40	storage
          172.16.7.50	ctrl01
          172.16.7.51	compute01
          172.16.7.52	compute02
          172.16.7.80	haproxy01

          ## Storage Network - stornet.example.com
          192.168.99.252	workstation-{{ guid }}.stornet.example.com
          192.168.99.40	storage.stornet.example.com
          192.168.99.50	ctrl01.stornet.example.com
          192.168.99.51	compute01.stornet.example.com
          192.168.99.52	compute02.stornet.example.com
          192.168.99.71	proxy01.stornet.example.com
          192.168.99.72	proxy02.stornet.example.com

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
