- name: Log in (obtain access token)
  community.okd.openshift_auth:
    username: "{{ openshift_cnv_username }}"
    password: "{{ openshift_cnv_password }}"
    host: "{{ openshift_cnv_api_uri }}"
  register: k8s_auth_results
