- name: Create routes with tls
  k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ route.name }}"
        namespace: "{{ openshift_cnv_project_name }}"
      spec:
        port:
          targetPort: "{{ route.targetPort }}"
        tls:
          termination: passthrough
          insecureEdgeTerminationPolicy: None
        to:
          kind: Service
          name: "{{ route.service }}"
  when: "{{ route.tls|default(False) == True}}"
  loop: "{{ instance.routes|default([]) }}"
  loop_control:
    loop_var: route

- name: Create routes without tls
  k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ route.name }}"
        namespace: "{{ openshift_cnv_project_name }}"
      spec:
        port:
          targetPort: "{{ route.targetPort }}"
        to:
          kind: Service
          name: "{{ route.service }}"
  when: "{{ route.tls|default(false) == false  }}"
  loop: "{{ instance.routes|default([]) }}"
  loop_control:
    loop_var: route


