---
- include_role:
    name: infra-cloud-tags
  when: cloud_tags_final is not defined

- debug: var=instances

- name: Create Instances
  register: r_openshift_cnv_instances
  loop: "{{ instances }}"
  loop_control:
    loop_var: _instance
  kubevirt_vm:
      state: running
      name: "{{ _instance.name }}"
      namespace: "{{ openshift_cnv_project_name }}"
      memory: "{{ _instance.memory }}"
      cpu_cores: "{{ _instance.cores }}"
      wait_timeout: 2400
      datavolumes:
        - name: "{{ _instance.image|replace('.','') }}-{{ guid }}"
          source:
            pvc:
              namespace: "default"
              name: "{{ _instance.image }}"
          pvc:
            accessModes:
              - ReadWriteMany
            volumeMode: Block
            storage: "{{ _instance.image_size }}"
            name: "{{ _instance.image|replace('.','') }}-{{ guid }}"

      definition:
        metadata:
          annotations: >-
            {{ cloud_tags_final
            | combine(_instance.tags | ec2_tags_to_dict) }}
      cloud_init_nocloud: 
        userData: |-
          #cloud-config
          ssh_authorized_keys:
            - {{ lookup('file', openshift_cnv_ssh_pub_key_path ) }}

- debug:
    var: r_openshift_cnv_instances
    verbosity: 3


- name: Create services for the nodes
  include_tasks: create_services.yaml
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance

- name: Create routes for the nodes
  include_tasks: create_routes.yaml
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance


