---
- debug: var=networks
  when: networks|default(False)

- name: Create Networks
  register: r_openshift_cnv_networks
  loop: "{{ networks|default([])}}"
  loop_control:
    loop_var: _network
  include_tasks: create_network.yaml


