- name: Create services for the instances
  k8s:
    definition: 
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ service.name }}{{ _instance_index+1 if instance.count|default(1)|int > 1 else '' }}"
        namespace: "{{ openshift_cnv_project_name }}"
      spec: "{{ spec | from_yaml }}"
  vars: # Trick to convert to integer
    spec: |
        ports:
        - port: {{ service.port }}
          protocol: "{{ service.protocol }}"
          targetPort: {{ service.targetPort }}
        selector:
          vm.cnv.io/name: "{{ instance.name }}{{ _instance_index+1 if instance.count|default(1)|int > 1 else '' }}"
  loop: "{{ range(1, instance.count|default(1)|int+1) | list }}"
  loop_control:
    index_var: _instance_index



