---
- name: Create Network(s)
  when: networks|default(False)
  block: 
    - name: Check if is locked
      k8s_info:
        kind: ConfigMap
        namespace: "default"
        name: "vlansused-lock"
      register: cm
      retries: 30
      delay: "{{ range(2,10) | random }}"
      until: cm.resources == []

    - name: Double check is not locked again
      k8s_info:
        kind: ConfigMap
        namespace: "default"
        name: "vlansused-lock"
      register: cm
      retries: 30
      delay: "{{ range(2,10) | random }}"
      until: cm.resources == []



    - name: Create a lock
      k8s:
        definition:
          kind: ConfigMap
          metadata:
            namespace: "default"
            name: "vlansused-lock"

    - name: Create Networks
      register: r_openshift_cnv_networks
      loop: "{{ networks|default([])}}"
      loop_control:
        loop_var: _network
      include_tasks: create_network.yaml

    - name: Remove the lock
      k8s:
        state: absent
        definition:
          kind: ConfigMap
          metadata:
            namespace: "default"
            name: "vlansused-lock"


