- debug: var=service.port
  loop: "{{ instance.services }}"
  loop_control:
    loop_var: service 

- debug: var=instance.services

- name: Create services for the instances
  loop: "{{ instance.services }}"
  loop_control:
    loop_var: service 
  k8s:
    definition: 
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ service.name }}"
        namespace: "{{ openshift_cnv_project_name }}"
      spec: "{{ spec | from_yaml }}"
  vars: # Trick to convert to integer
    spec: |
        ports:
        - port: {{ service.port }}
          protocol: "{{ service.protocol }}"
          targetPort: {{ service.targetPort }}
        selector:
          vm.cnv.io/name: "{{ instance.name }}"


