- name: Create a SSH service for internal connections
  k8s:
    definition: 
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ instance.name }}{{ _instance_index+1 if instance.count|default(1)|int > 1 else '' }}"
        namespace: "{{ openshift_cnv_project_name }}"
      spec:
        ports:
        - port: 22
          protocol: TCP
          targetPort: 22
        selector:
          vm.cnv.io/name: "{{ instance.name }}{{ _instance_index+1 if instance.count|default(1)|int > 1 else '' }}"
  loop: "{{ range(1, instance.count|default(1)|int+1) | list }}"
  loop_control:
    index_var: _instance_index


- name: Create services for the instances
  loop: "{{ instance.services|default([]) }}"
  loop_control:
    loop_var: service 
  include_tasks: create_service.yaml


