---
- name: Create network {{ _network.name }}
  k8s:
    definition:
      apiVersion: v1
      kind: NetworkAttachmentDefinition
      metadata:
        name: "{{ _network.name }}"
        namespace: "{{ openshift_cnv_project_name }}"
      spec:
        config: "{{ config | to_json }}"
  vars: 
    config: "{'cniVersion':'0.3.1','type':'cnv-bridge','bridge':'br-internal','vlan': {{ available_vlan_ids[_network_idx] }}, 'mtu': 9000}"
#      config: "{'name':'{{ _network.name }}','cniVersion':'0.3.1','plugins':[{'type':'cnv-bridge','bridge':'br-internal','vlan': {{ available_vlan_id }}},{'type':'cnv-tuning'}]}"
