---
- include_role:
    name: infra-cloud-tags
  when: cloud_tags_final is not defined

- debug: var=instances
- set_fact:
    r_openshift_cnv_instances: []
- name: Create Instances
  #register: r_openshift_cnv_instances
  loop: "{{ instances }}"
  loop_control:
    loop_var: _instance
  include_tasks: create_instance.yaml
      

- debug:
    var: r_openshift_cnv_instances


- name: Create services for the nodes
  include_tasks: create_services.yaml
  loop: "{{ instances }}"
  loop_control:
    loop_var: _instance

- name: Create routes for the nodes
  include_tasks: create_routes.yaml
  loop: "{{ instances }}"
  loop_control:
    loop_var: _instance


