- name: Create a SSH service for internal connections for node {{ _instance.name }}
  vars:
    _instance_name: "{{ _instance.name }}{{ _index+1 if _instance.count|d(1)|int > 1 }}"
  k8s:
    definition: 
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ _instance_name }}"
        namespace: "{{ openshift_cnv_project_name }}"
      spec:
        ports:
        - port: 22
          protocol: TCP
          targetPort: 22
        selector:
          vm.cnv.io/name: "{{ _instance_name }}"
  loop: "{{ range(1, _instance.count|default(1)|int+1) | list }}"
  loop_control:
    index_var: _index


- name: Create services for the instances
  loop: "{{ _instance.services|default([]) }}"
  loop_control:
    loop_var: service 
  include_tasks: create_service.yaml


