---
- name: Create Network(s)
  when: networks|default(False)
  block: 
    - name: Check which networks have to be created
      include_tasks: check_network.yaml
      loop: "{{ networks|default([])}}"
      loop_control:
        loop_var: _network

    - name: Get the ConfigMap of used vlans
      k8s_info:
        kind: ConfigMap
        namespace: default
        name: vlansused
      register: vlansused

    - name: Obtain available VLANs
      set_fact:
        available_vlan_ids: "{{ (range(2,200)|difference(vlansused.resources[0].data.vlans|default('[]') | from_json))[:_networks_to_create|length]}}"

    - name: Update ConfigMap to set this vlan will be in used
      k8s:
        namespace: default
        apply: yes
        definition:
          kind: ConfigMap
          apiVersion: v1
          metadata:
            name: vlansused
            resourceVersion: "{{ vlansused.resources[0].metadata.resourceVersion }}"
          data:
            vlans: "{{ ((vlansused.resources[0].data.vlans | from_json) + available_vlan_ids) | to_json}}"

  rescue: 
    - include_tasks: create_networks.yaml

- name: Create Networks
  register: r_openshift_cnv_networks
  loop: "{{ networks|default([])}}"
  loop_control:
    loop_var: _network
    index_var: _network_idx
  include_tasks: create_network.yaml



