---
- name: Get a list of Network
  k8s_info:
    kind: NetworkAttachmentDefinition
    namespace: "{{ openshift_cnv_project_name }}"
  register: r_network_list

- name: Set a list of vlan IDS to be released
  set_fact:
    release_ids: "{{ release_ids|default([]) + [(item.spec.config | from_json)| json_query(query)] }}"
  vars:
    query: "vlan"
  loop: "{{ r_network_list.resources| list }}"

- name: Update ConfigMap if needed
  when: release_ids|default(False)
  block:
    - name: Check if is locked
      k8s_info:
        kind: ConfigMap
        namespace: "default"
        name: "vlansused-lock"
      register: cm
      retries: 30
      delay: 5
      until: cm.resources == []

    - name: Create a lock
      k8s:
        definition:
          kind: ConfigMap
          metadata:
            namespace: "default"
            name: "vlansused-lock"

    - name: Get the ConfigMap of used vlans
      k8s_info:
        kind: ConfigMap
        namespace: default
        name: vlansused
      register: vlansused

    - name: Update ConfigMap to remove the the VLANs used by the project
      k8s:
        namespace: default
        definition:
          kind: ConfigMap
          apiVersion: v1
          metadata:
            name: vlansused
          data:
            vlans: "{{ vlansused.resources[0].data.vlans | from_json | difference(release_ids) | to_json }}"

    - name: Remove the lock
      k8s:
        state: absent
        definition:
          kind: ConfigMap
          metadata:
            namespace: "default"
            name: "vlansused-lock"	
