---
- name: Get a list of Network
  k8s_info:
    kind: NetworkAttachmentDefinition
    namespace: "{{ openshift_cnv_project_name }}"
  register: r_network_list

- name: Set a list of vlan IDS to be released
  set_fact:
    release_ids: "{{ release_ids|default([]) + (item.spec.config | from_json).plugins | json_query(query) }}"
  vars:
    query: "[?type=='cnv-bridge'].vlan"
  loop: "{{ r_network_list.resources| list }}"

- name: Get the ConfigMap of used vlans
  when: release_ids|default(False)
  k8s_info:
    kind: ConfigMap
    namespace: default
    name: vlansused
  register: vlansused

- name: Update ConfigMap to remove the the VLANs used by the project
  when: release_ids|default(False)
  k8s:
    namespace: default
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: vlansused
      data:
        vlans: "{{ vlansused.resources[0].data.vlans | from_json | difference(release_ids) | to_json }}"

