---
- include: authentication.yaml
- when: ACTION == 'provision'
  block:
    - include_tasks: create_project.yaml
    - include_tasks: ssh_key.yaml
    - include_tasks: create_instances.yaml
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: False


- when: ACTION == 'destroy'
  block:
     #- include_tasks: delete_instances.yaml
     - include_tasks: delete_project.yaml
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: False


- when: ACTION in ['status', 'start', 'stop']
  block:
     - include_tasks: "{{ ACTION }}_instances.yaml"
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: False


