---
- name: Log in (obtain access token)
  k8s_auth:
    username: "{{ openshift_cnv_username }}"
    password: "{{ openshift_cnv_password }}"
    host: "{{ openshift_cnv_api_uri }}"
  register: k8s_auth_results

- when: ACTION == 'provision'
  block:
    - include_tasks: create_project.yaml
    - include_tasks: ssh_key.yaml
    - include_tasks: create_networks.yaml
    - include_tasks: create_instances.yaml
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      validate_certs: False


- when: ACTION == 'destroy'
  block:
     #- include_tasks: delete_instances.yaml
     - include_tasks: delete_networks.yaml
     - include_tasks: delete_project.yaml
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      validate_certs: False


- when: ACTION in ['status', 'start', 'stop']
  block:
     - include_tasks: "{{ ACTION }}_instances.yaml"
  module_defaults:
    group/k8s:
      host: "{{ openshift_cnv_api_uri }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      validate_certs: False


