---
- name: Get a list of VMs
  k8s_info:
    kind: VirtualMachine
    namespace: "{{ openshift_cnv_project_name }}"
  register: r_vm_list


- name: Start the Virtual Machines
  loop: "{{ r_vm_list.resources }}"
  loop_control:
    loop_var: _instance
  kubevirt_vm:
      state: running
      name: "{{ _instance.metadata.name }}"
      namespace: "{{ openshift_cnv_project_name }}"
