---
- name: Get a list of VMIs
  k8s_info:
    kind: VirtualMachineInstance
    namespace: "{{ openshift_cnv_project_name }}"
  register: r_vmi_list


- name: Stop the Virtual Machines
  loop: "{{ r_vmi_list.resources }}"
  loop_control:
    loop_var: _instance
  kubevirt_vm:
      state: stopped
      name: "{{ _instance.metadata.name }}"
      namespace: "{{ openshift_cnv_project_name }}"
