---
# The type of cloud provider this will be deployed to
cloud_provider: openshift_cnv

# This is the user that Ansible will use to connect to the nodes it is
# configuring from the admin/control host
ansible_user: cloud-user
remote_user: cloud-user

# OpenShift CNV project name
openshift_cnv_project_name: "{{ env_type }}-{{ guid }}"


### Networking and DNS (AWS)

subdomain_base_short: "{{ guid }}"

subdomain_base: "{{ subdomain_base_short }}{{ subdomain_base_suffix }}"
zone_internal_dns: "{{ guid }}.internal."
chomped_zone_internal_dns: "{{ guid }}.internal"

bastion_instance_image: rhel-labs-9.2

#
# Instances to deploy
#

instances:
  - name: "{{ bastion_hostname | default('bastion') }}"
    count: 1
    unique: true
    public_dns: true
    dns_loadbalancer: true
    floating_ip: true
    image: "{{ bastion_instance_image | default(default_instance_image) }}"
    memory: 8G
    cores: 4
    image_size: 100Gi
    tags:
      - key: "AnsibleGroup"
        value: "bastions,showroom"
      - key: "ostype"
        value: "linux"
...
