---

- name: Step 00xxxxx software
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step005
    - software

  tasks:

    - name: "Software tasks Started"
      ansible.builtin.debug:
        msg: "Software tasks Started"

- name: Run setup scripts for the instances
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Excecute script if exists
      script: "labs/scripts/{{ lab_name }}/setup-{{ inventory_hostname }}"
      when: "{{ lookup('ansible.builtin.fileglob', 'labs/scripts/' + lab_name + '/setup-' + inventory_hostname) != [] }}"

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:

    - name: "Software checks completed successfully"
      ansible.builtin.debug:
        msg: "Software checks completed successfully"

- name: Run software_validation playbook
  when: >-
    agd_software_validation | default(false) | bool
      or agd_validation | default(false) | bool
  ansible.builtin.import_playbook: software_validation.yml
  tags:
    - software_validation
    - agd_validation

...
