---
- import_playbook: ../../setup_runtime.yml

- name: Have the OpenShift installer cleanup what it did
  hosts: bastions
  gather_facts: false
  become: false
  tasks:
  - name: Wait for the bastion host to be available
    wait_for_connection:
      timeout: 60
    register: bwait
    ignore_errors: true
  - fail:

- name: Destroy environment on OpenShift CNV
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Run host-ocp4-assisted-destroy role
    include_role:
      name: host-ocp4-assisted-destroy


- name: Import default cloud provider destroy playbook
  import_playbook: "../../cloud_providers/{{ cloud_provider }}_destroy_env.yml"
