---
- name: Step 000 pre-software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Pre-Software tasks Started"

- name: Configure bastion with repositories
  hosts:
  - bastions
  become: true
  gather_facts: false
  tags:
  - step003
  - common_tasks
  roles:
  - role: set-repositories
    when: repo_method is defined
  - role: common
    when: install_common | bool
  - role: set_env_authorized_key
    when: set_env_authorized_key | bool
  tasks:
  - name: Add GUID to /etc/skel/.bashrc
    lineinfile:
      path: "/etc/skel/.bashrc"
      regexp: "^export GUID"
      line: "export GUID={{ guid }}"

- name: Step 003.1 - Configuring Bastion Hosts
  hosts: bastions
  become: true
  roles:
  - role: bastion-lite
    when: install_bastion | bool
  - role: bastion-student-user
    when: install_student_user | bool
  tags:
  - step003.1
  - bastion_tasks
  tasks:
  - name: Setup Student SSH Key
    when:
    - install_student_user | bool
    - student_name is defined
    - env_authorized_key is defined
    block:
    - name: Copy SSH private key to student user .ssh directory
      copy:
        src: "/root/.ssh/{{ env_authorized_key }}.pem"
        dest: "~{{ student_name }}/.ssh/{{ env_authorized_key }}.pem"
        mode: u=rw,go=
        owner: "{{ student_name }}"
        remote_src: true

    - name: Copy SSH public key to student user .ssh directory
      copy:
        src: "/root/.ssh/{{ env_authorized_key }}.pub"
        dest: "~{{ student_name }}/.ssh/{{ env_authorized_key }}.pub"
        mode: u=rw,go=
        owner: "{{ student_name }}"
        remote_src: true

    - name: Copy SSH config to student user .ssh directory
      copy:
        src: "/root/.ssh/config"
        dest: "~{{ student_name }}/.ssh/config"
        mode: u=rw,go=
        owner: "{{ student_name }}"
        remote_src: true

- name: Create a Python3 VirtualEnv for use in the k8s Ansible tasks
  hosts: bastions
  gather_facts: false
  become: true
  tasks:
  - name: Setup k8s virtualenv
    include_role:
      name: host_virtualenv
    vars:
      host_virtualenv_path: /opt/virtualenvs/k8s
      # Merge base k8s requirements with cloud provider specific requirements
      host_virtualenv_requirements:
      - requirements_k8s.txt
      - requirements_{{ cloud_provider }}.txt

  - name: Install git
    package:
      state: present
      name:
      - git

- name: Install Azure CLI
  hosts: bastions
  gather_facts: false
  become: true
  tasks:
    - name: Install Azure CLI
      when: install_aro | default(false) | bool
      block:
        - name: Import Azure CLI GPG key
          ansible.builtin.rpm_key:
            state: present
            key: https://packages.microsoft.com/keys/microsoft.asc

        - name: Add Azure CLI repository
          ansible.builtin.yum:
            name: https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm
            state: present

        - name: Install Azure CLI package
          ansible.builtin.yum:
            name: azure-cli
            state: latest

        - name: Install git and pip
          ansible.builtin.package:
            name:
              - git
              - python3-pip
            state: latest

- name: Stash Creds For Azure CLI
  hosts: bastions
  gather_facts: false
  become: true
  become_user: "{{ remote_user }}"
  tasks:
    - name: Stash Creds For Azure CLI
      when: install_aro | default(false) | bool
      block:
        - name: Log into Azure SP and stash creds in remote user
          ansible.builtin.command: >-
            az login --service-principal -u "{{ hostvars.localhost.azappsp.service_principals[0].app_id }}"
            -p="{{ hostvars.localhost.azpass }}" --tenant="{{ azure_tenant }}"

- name: Set GUID in bashrc
  hosts: bastions
  gather_facts: false
  become: true
  become_user: "{{ remote_user }}"
  tasks:
  - name: "Add GUID to /home/{{ remote_user }}.bashrc"
    lineinfile:
      path: "/home/{{ remote_user }}/.bashrc"
      regexp: "^export GUID"
      line: "export GUID={{ guid }}"

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Pre-Software checks completed successfully"
