---
default_key_name: ~/.ssh/{{key_name|default('')}}.pem
remote_user_map:
  ec2: ec2-user
  azure: azure
  osp: cloud-user
  gcp: gcpuser
  equinix_metal: root
<<<<<<< HEAD
<<<<<<< HEAD
  vmc: cloud-user
=======
  openshift_cnv: cloud-user
>>>>>>> a73492622 (New cloud config and example)
=======
  openshift_cnv: cloud-user
>>>>>>> 6ac4bc0c57ee65c726a3aee907e778de42d5213c
