- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
    - pre_infrastructure
    - generate_env_keys
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"
        
    - name: Call create_ssh_provision_key role
      when: set_env_authorized_key | bool
      import_role:
        name: create_ssh_provision_key
      tags:
        - generate_env_keys   

    - name: Include tasks to find snapshot in AWS
      when: cloud_provider == 'ec2'
      include_tasks: find_snapshot.yml
