---
roles:
- src: https://github.com/redhat-cop/infra-ansible.git
  name: infra-ansible
  version: v2.0.8

- name: redhat_sap.sap_rhsm
  src: https://github.com/redhat-sap/sap-rhsm

collections:
- name: community.general
  version: 4.6.1
- name: ansible.posix
  version: 1.3.0
- name: openstack.cloud
  version: 1.7.2
