---
hcp_ssh_authorized_key: "{{ lookup('ansible.builtin.file', hostvars.localhost.ssh_provision_pubkey_path) }}"
hcp_cluster_name: "{{ guid }}"
hcp_cluster_version: "{{ ocp4_installer_version | default('4.13') }}"
hcp_workers_cores: 16
hcp_workers_memory: 64Gi
hcp_storage_class: "ocs-external-storagecluster-ceph-rbd"
hcp_ocp_namespace: "{{ sandbox_openshift_namespace | default(env_type + '-' + guid)}}"
hcp_cluster_issuer: "letsencrypt"
hcp_admin_password_length: 16
hcp_user_password_length: 16
hcp_user_base: "user"
hcp_admin_user: "admin"
hcp_user_passwords: []
hcp_controller_availability_policy: SingleReplica
hcp_authentication: "htpasswd"
hcp_etcd_pvc_size: "8Gi"
hcp_worker_cores: 16
hcp_worker_memory: 32Gi
hcp_worker_root_voume_size: 32Gi
