- name: Get Sandbox Student IPs
  uri:
    url: "{{ nsxt_proxy_url }}/policy/api/v1/infra/domains/mgw/groups/Sandbox_Student_IPs"
    method: GET
    headers:
      csp-auth-token: "{{ _nsxt_token }}"
    return_content: yes
  register: _sandbox_public_ips

- name: Set a new variable appending the IP to the Sandbox Student IPs
  set_fact: 
    _sandbox_public_ips_new: "{{ _sandbox_public_ips.json.expression.0.ip_addresses|default([]) + [vmc_vcenter_student_ip] }}"

- name: Update list of IPs for Sandbox Student IPs
  uri:
    url: "{{ nsxt_proxy_url }}/policy/api/v1/infra/domains/mgw/groups/Sandbox_Student_IPs"
    method: PATCH
    headers:
      csp-auth-token: "{{ _nsxt_token }}"
    body_format: json
    body:
      display_name: "Sandbox Student IPs"
      expression:
      - resource_type: "IPAddressExpression"
        ip_addresses: "{{ _sandbox_public_ips_new }}"
    return_content: yes
  register: return_update_ips
