---
- name: Remove rocket chat project
  kubernetes.core.k8s:
    name: "{{ ocp4_workload_rocket_chat_namespace }}"
    api_version: v1
    kind: Project
    state: absent
  register: project_result
  until: project_result is succeeded
  retries: 10
  delay: 10
