---
# -------------------------------------------------
# OpenShift Network settings
# -------------------------------------------------
subdomain_base_short: "{{ guid }}"
subdomain_base_suffix: "{{ openshift_cnv_apps_domain }}"
subdomain_base: "{{ subdomain_base_short }}.{{ subdomain_base_suffix }}"


# OpenShift CNV project name
openshift_cnv_project_name: "{{ env_type }}-{{ guid }}"
ansible_user: cloud-user
remote_user: cloud-user
use_dynamic_dns: true


# Bastion Configuration
default_instance_image: rhel-8.7
default_rootfs_size: 30Gi

bastion_cores: 2
bastion_memory: 4G

nodes_cores: 2
nodes_memory: 4G


# -------------------------------------------------
# OpenShift CNV Instances
# -------------------------------------------------
instances:
  - name: "{{ bastion_instance_name | default('ansible-1') }}"
    count: 1
    unique: true
    memory: "{{ bastion_memory }}"
    cores: "{{ bastion_cores }}"
    image_size: "{{ bastion_rootfs_size | default(default_rootfs_size) }}"
    image: "{{ bastion_instance_image | default(default_instance_image) }}"
    metadata:
      - AnsibleGroup: "bastions"
      - function: bastion
      - user: "{{ student_name }}"
      - project: "{{ project_tag }}"
      - ostype: linux
      - Purpose: "{{ purpose }}"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ guid }}"
    networks:
      - default
    services:
      - name: ansible-1
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: ansible-https
          - port: 80
            protocol: TCP
            targetPort: 80
            name: ansible-http
          - port: 22
            protocol: TCP
            targetPort: 22
            name: ansible-ssh
    routes:
      - name: ansible-https
        host: ansible-1
        service: ansible-1
        targetPort: 443
        tls: true
      - name: ansible-http
        host: ansible-1
        service: ansible-1
        targetPort: 80
        tls: false
        path: "/.well-known/"

  - name: "node"
    count: 3
    public_dns: false
    image: "{{ nodes_instance_image | default(default_instance_image) }}"
    memory: "{{ nodes_memory | default(default_memory) }}"
    cores: "{{ nodes_cores | default(default_cores) }}"
    image_size: "{{ node_rootfs_size | default(default_rootfs_size)  }}"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
      - key: "ostype"
        value: "rhel"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"
    rootfs_size: "{{ default_rootfs_size }}"
    networks:
      - default

# -------------------------------------------------
# Ansible hosts_template.j2 inventory groups
# -------------------------------------------------
inventory_groups:
  - nodes
