- name: Save to OSP images or upload to IBM Cloud
  hosts: migration
  gather_facts: false
  tags: save_images
  tasks:
    - import_role:
        name: infra-osp-save-images

- name: Output user access information
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: osp user.info
      when: cloud_provider == "osp"
      block:
      - name: Show website access information
        agnosticd_user_info:
          msg: "{{ item }}"
        loop:
          - " "
          - "You can access your lab using web: https://console-openshift-console.apps.{{ guid }}.{{ osp_cluster_dns_zone }}/"

      - name: Print Student SSH access as user.info
        agnosticd_user_info:
          msg: "{{ item }}"
        loop:
          - " "
          - "You can access your bastion via SSH:"
          - "SSH Access: ssh {{ student_name }}@provision.{{ guid }}.{{ osp_cluster_dns_zone }}"
        when: install_student_user | bool

      - name: Print Student SSH password as user.info
        agnosticd_user_info:
          msg: "SSH password: {{ student_password | default(hostvars[groups.bastions.0].student_password) }}"
        when:
          - print_student_password | default(true) | bool
          - install_student_user | bool

    - name: openshift-cnv user.info
      when: cloud_provider == 'openshift_cnv'
      block:
        - name: print out user.info
          agnosticd_user_info:
            msg: "{{ item }}"
          loop:
            - "To access console via browser:"
            - "https://console-openshift-console.{{ guid }}.apps.{{ openshift_cnv_apps_domain }}"
            - ""
            - "To access bastion via SSH:"
            - "ssh {{ student_name }}@ssh.{{ openshift_cnv_apps_domain }} -p {{ hostvars[groups['bastions'][0]].bastion_ssh_port }}"
            - "Enter ssh password when prompted: {{ hostvars[groups['bastions'][0]]['student_password'] }}"

        - name: Save user data
          agnosticd_user_info:
            data:
              ssh_command: "ssh {{ student_name }}@ssh.{{ openshift_cnv_apps_domain }} -p {{ hostvars[groups['bastions'][0]].bastion_ssh_port }}"
              ssh_password: "{{ hostvars[groups['bastions'][0]]['student_password'] }}"


- name: Output lab console
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print labconsole information as user.info
      when: osp_migration_report_labconsole | bool
      agnosticd_user_info:
        msg: "{{ item }}"
      loop:
        - ""
        - "In case you need to access to the console of the VMs for your lab:"
        - "URL: {{ osp_migration_labconsole_url }}"
        - "Username: {{ student_name }}"
        - "Password: *your opentlc password*"

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
