---
# vim: set ft=ansible
# Implement your Workload deployment tasks here

- name: Create PVC for Image Registry
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/pvc.yaml.j2' ) | from_yaml }}"

- name: Enable image registry
  command: |
      oc patch configs.imageregistry.operator.openshift.io cluster
      --type merge --patch '{"spec":{"storage":{"pvc":{"claim":"{{ pvc_name }}"}}, "managementState": "Managed"}}'
