---
# vim: set ft=ansible
# Implement your Workload deployment tasks here

- name: Create PVC for Image Registry
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/pvc.yaml.j2' ) | from_yaml }}"

- name: Enable image registry
  command: |
      oc patch configs.imageregistry.operator.openshift.io cluster
      --type merge --patch '{"spec":{"storage":{"pvc":{"claim":"{{ pvc_name }}"}}, "managementState": "Managed"}}'

- name: If PVC is RWO then specify replicas 1 and rolloutStrategy to Recreate
  command: |
      oc patch config.imageregistry.operator.openshift.io/cluster
      --type=merge -p '{"spec":{"rolloutStrategy":"Recreate","replicas":1}}'
  when: pvc_accessmode == "ReadWriteOnce"
