---
galaxy_info:
  role_name: ocp4_workload_odf_config
  author: Alberto Gonzalez
  description: |
    Configure ODF after being installed
  license: MIT
  min_ansible_version: 2.9
  platforms: []
  galaxy_tags:
    - ocp
    - openshift
    - odf
dependencies: []
