---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: hcp
  namespace: {{ namespace }}
spec:
  arch: amd64
  clusterName: hcp
  management:
    autoRepair: false
    upgradeType: Replace
  nodeDrainTimeout: 0s
  platform:
    kubevirt:
      attachDefaultNetwork: true
      compute:
        cores: 16
        memory: 32Gi
        qosClass: Guaranteed
      rootVolume:
        persistent:
          size: 32Gi
        type: Persistent
    type: KubeVirt
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.16.10-x86_64
  replicas: 3
status:
  replicas: 0
