---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ guid }}
  name: "svc-{{ guid }}-apps"
  namespace: "{{ namespace }}"
spec:
  ports:
    - name: https-443
      port: 443
      protocol: TCP
      targetPort: {{ https_nodeport.stdout }}
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: {{ http_nodeport.stdout }}
  selector:
    kubevirt.io: virt-launcher
  type: LoadBalancer
