---
# TODO: (could be used bu other services?)

- name: Get list of domains for Parasol cert 
  ansible.builtin.shell: "jq -r '.[].Certificates[].domain.main' {{ showroom_user_orchestration_dir }}/acme.json"
  changed_when: false
  register: r_domains_output
  vars:
    acmejsonfile: "{{ showroom_user_orchestration_dir }}/acme.json"
    outdir: "{{ showroom_user_orchestration_dir }}"

- name: Debug Extract certificate bundle and private key for each domain
  ansible.builtin.debug:
    var: "{{ domain }}"
  loop: "{{ r_domains_output.stdout_lines }}"
  loop_control:
    loop_var: domain

- name: Extract certificate bundle and private key for each domain
  ansible.builtin.include_tasks: extract_cert_key.yml
  loop: "{{ r_domains_output.stdout_lines }}"
  loop_control:
    loop_var: domain
  vars:
    acmejsonfile: "{{ showroom_user_orchestration_dir }}/acme.json"
    outdir: "{{ showroom_user_orchestration_dir }}"

- name: Enable and Start showroom service
  ansible.builtin.service:
    name: showroom.service
    state: restarted
