---
# tasks file for fedora-cuda

- name: copy over cuda dnf repo
  become: yes
  copy:
    src: ../files/cuda-fedora39.repo
    dest: /etc/yum.repos.d/cuda-fedora39.repo
    owner: root  # Optional: specify the owner of the file on the remote machine
    group: root  # Optional: specify the group of the file on the remote machine
    mode: '0644'  # Optional: specify permissions

- name: copy over cuda dnf repo
  become: yes
  copy:
    src: ../files/rpmfusion-free.repo
    dest: /etc/yum.repos.d/rpmfusion-free.repo
    owner: root  # Optional: specify the owner of the file on the remote machine
    group: root  # Optional: specify the group of the file on the remote machine
    mode: '0644'  # Optional: specify permissions

- name: copy over cuda dnf repo
  become: yes
  copy:
    src: ../files/rpmfusion-nonfree.repo
    dest: /etc/yum.repos.d/rpmfusion-nonfree.repo
    owner: root  # Optional: specify the owner of the file on the remote machine
    group: root  # Optional: specify the group of the file on the remote machine
    mode: '0644'  # Optional: specify permissions
        
- name: Install pciutils
  become: yes
  dnf:
    name: pciutils
    state: present
- name: Install akmod-nvidia
  become: yes
  dnf:
    name: akmod-nvidia
    state: present
# - name: Install xorg-x11-drv-nvidia-cuda
#   become: yes
#   dnf:
#     name: xorg-x11-drv-nvidia-cuda
#     state: present
- name: Install cuda-toolkit-12-4
  become: yes
  dnf:
    name: cuda-toolkit-12-4
    state: present
- name: Install nvtop
  become: yes
  dnf:
    name: nvtop
    state: present
 
- name: Check video driver
  shell: lspci -nn -k | grep -A 2 -e VGA -e 3D
  register: video_driver_check
  changed_when: false
  ignore_errors: true

- name: Output video driver check
  debug:
    var: video_driver_check.stdout_lines

## Need to add here, that this reboot only happens if the output of the video driver check does NOT return "Kernel driver in use: nvidia"
- name: Reboot the machine
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5    # Time in seconds to wait for the host to shutdown and start the connection attempt.
    reboot_timeout: 600   # Time in seconds to wait for the machine to reboot.
    pre_reboot_delay: 0   # Time in seconds to wait before shutting down (if you need to warn users).
    post_reboot_delay: 30 # Time in seconds to wait after the machine is back up, before continuing with subsequent tasks.
    test_command: uptime  # Command to execute repeatedly until the target machine responds, indicating it's back online.

- name: Check video driver
  shell: lspci -nn -k | grep -A 2 -e VGA -e 3D
  register: video_driver_check
  changed_when: false
  ignore_errors: true

- name: Output video driver check
  debug:
    var: video_driver_check.stdout_lines
