---
- name: Step 001 Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step001
    - infrastructure
  tasks:
    - debug:
        msg: "Step 001 Infrastructure - Starting"

    - name: Run infra-aws-open-environment Role
      when: cloud_provider == 'ec2'
      include_role:
        name: infra-aws-open-environment
      vars:
        ACTION: provision

    - name: Run infra-vmc-resources Role
      when: cloud_provider == 'vmc'
      include_role:
        name: infra-vmc-resources
      vars:
        ACTION: provision
