---
- name: Retrieve Ingress config
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: r_ingress_config

- name: Get OpenShift Apps Domain
  set_fact:
    _ocp4_workload_blackhat_secured_container_pipelines_dev_ocp_apps_domain: "{{ r_ingress_config.resources[0].spec.domain }}"

- name: Print Access information
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
  - ""
  - "Globex Dev UI url: https://globex-ui-{{ ocp4_workload_blackhat_secured_container_pipelines_app_namespace }}.{{ _ocp4_workload_blackhat_secured_container_pipelines_dev_ocp_apps_domain }}"  # yamllint disable-line rule:line-length
  - "Globex Dev UI username: coolstore@redhat.com"
  - "Globex Dev UI password: coolstore"

- name: Print Access information
  agnosticd_user_info:
    data:
      app_dev_url: "https://globex-ui-{{ ocp4_workload_blackhat_secured_container_pipelines_app_namespace }}.{{ _ocp4_workload_blackhat_secured_container_pipelines_dev_ocp_apps_domain }}"  # yamllint disable-line rule:line-length
      app_dev_username: "coolstore@redhat.com"
      app_dev_password: "coolstore"
      openshift_cluster_console_url: https://console-openshift-console.{{ _ocp4_workload_blackhat_secured_container_pipelines_dev_ocp_apps_domain }}  # yamllint disable-line rule:line-length
      openshift_cluster_admin_username: "{{ ocp4_workload_authentication_admin_user }}"
      openshift_cluster_admin_password: "{{ common_password }}"
      bastion_public_hostname: "{{ bastion_public_hostname }}"
      bastion_ssh_password: "{{ bastion_ssh_password }}"
      bastion_ssh_user_name: "{{ bastion_ssh_user_name }}"
      rhacs_console_url: https://central-{{ ocp4_workload_blackhat_secured_container_pipelines_stackrox_namespace }}.{{ _ocp4_workload_blackhat_secured_container_pipelines_dev_ocp_apps_domain }}"  # yamllint disable-line rule:line-length
      rhacs_admin_user_name: admin
      rhacs_admin_password: "{{ common_password }}"
      code_server_url: https://codeserver-codeserver.{{ _ocp4_workload_blackhat_secured_container_pipelines_dev_ocp_apps_domain }}"  # yamllint disable-line rule:line-length
      code_server_password: "{{ common_password }}"

- name: Deploy Bookbag
  include_role:
    name: bookbag
  vars:
    ACTION: create
    bookbag_git_repo: "{{ ocp4_workload_blackhat_secured_container_pipelines_bookbag_repo }}"
    bookbag_git_version: "{{ ocp4_workload_blackhat_secured_container_pipelines_bookbag_revision }}"