---
- name: Determine cluster wildcard domain
  kubernetes.core.k8s_info:
    api_version: operator.openshift.io/v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
  register: r_ingress_controller

- name: Save cluster apps domain variable
  ansible.builtin.set_fact:
    _ocp4_workload_mad_roadshow_apps_domain: "{{ r_ingress_controller.resources[0].status.domain }}"

- name: Get Gitea instance
  kubernetes.core.k8s_info:
    api_version: pfe.rhpds.com/v1
    kind: Gitea
    name: "{{ ocp4_workload_mad_roadshow_gitea_instance }}"
    namespace: "{{ ocp4_workload_mad_roadshow_gitea_project }}"
  register: r_gitea

- name: Set up GitOps environment
  when: ocp4_workload_mad_roadshow_gitops_setup | bool
  block:
  - name: Create demo namespaces for all users
    vars:
      _ocp4_workload_mad_roadshow_namespace: >-
        {{ ocp4_workload_mad_roadshow_demo_namespace_prefix }}{{
           ocp4_workload_mad_roadshow_gitea_user_prefix }}{{ n }}
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', 'apps/namespace.yaml.j2' ) | from_yaml }}"
    loop: "{{ range(1, ocp4_workload_mad_roadshow_gitea_user_count | int + 1) | list }}"
    loop_control:
      loop_var: n
      label: "{{ ocp4_workload_mad_roadshow_gitea_user_prefix }}{{ n }}"

- name: Setup - RHDH
  include_tasks:
    file: ./rhdh-main.yml

# -------------------
# AgnosticD User Info
# -------------------
- name: Save AgnosticD information for all users
  when: ocp4_workload_mad_roadshow_gitops_setup | bool
  agnosticd_user_info:
    user: "{{ ocp4_workload_mad_roadshow_gitea_user_prefix }}{{ n }}"
    data:
      user: "{{ ocp4_workload_mad_roadshow_gitea_user_prefix }}{{ n }}"
      gitea_url: >-
        {{ r_gitea.resources[0].spec.giteaSsl | bool | ternary( 'https', 'http' ) }}://{{
           r_gitea.resources[0].status.giteaHostname }}/{{
           ocp4_workload_mad_roadshow_gitea_user_prefix }}{{ n }}
      retail_namespace: "{{ ocp4_workload_mad_roadshow_demo_namespace_prefix }}{{ ocp4_workload_mad_roadshow_gitea_user_prefix }}{{ n }}"
      cicd_namespace: "{{ ocp4_workload_mad_roadshow_pipeline_namespace_prefix }}{{ ocp4_workload_mad_roadshow_gitea_user_prefix }}{{ n }}"
  loop: "{{ range(1, ocp4_workload_mad_roadshow_gitea_user_count | int + 1) | list }}"
  loop_control:
    loop_var: n
    label: "{{ ocp4_workload_mad_roadshow_gitea_user_prefix }}{{ n }}"

- name: Install Showroom
  ansible.builtin.include_tasks: showroom.yml
