---
- name: Import default destroy playbook
  import_playbook: ../../cloud_providers/{{cloud_provider}}_destroy_env.yml

- name: Delete VMs on VMWare
  hosts: localhost
  connection: local
  become: false
  tasks:
  - name: Destroy webapp VMs
    ansible.builtin.include_tasks: vcenter-remove-webapp-vms.yml

  - name: Remove access
    ansible.builtin.include_tasks: vcenter-remove_access.yml
